server:
  port: 30100

spring:
  application:
    name: checkin-backend
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接池配置
    hikari:
      minimum-idle: 5 # 最小连接数
      maximum-pool-size: 20 # 最大连接数
      connection-timeout: 5000 # 连接超时时间（毫秒）
      idle-timeout: 180000 # 空闲连接超时时间（毫秒）
      max-lifetime: 600000 # 连接最大生命周期（毫秒）
      validation-timeout: 5000 # 连接验证超时时间（毫秒）
      leak-detection-threshold: 60000 # 连接泄漏检测阈值（毫秒）
      pool-name: CheckinHikariPool # 连接池名称
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type: TRACE

# JWT配置
jwt:
  secret:
  expiration:

# 微信配置
wechat:
  appid:
  secret: